server:
  context-path: /codenotfound
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnf
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
